services:
  mongodb:
    image: mongo:7.0
    container_name: trabalho-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: trabalho_mongodb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
